### ISSUE TITLE
Send to Skyline throws exception on Skyline 21.1

### ISSUE THREAD

**Issue by nilshoffmann** [lifs-tools/lipidcreator#15] opened 2021-06-09 14:38 UTC
Skyline 21.1 with LipidCreator 1.2.0.772 throws the following exception when I try to send a transition list to Skyline.

```
2021-06-09 16:30:51,855 [1] INFO  LipidCreator.LipidCreator - LipidCreator is connected to Skyline file: ''
2021-06-09 16:30:51,869 [1] INFO  LipidCreator.LipidCreator - Running LipidCreator version 1.2.0.772 in skyline tool mode on Win32NT
2021-06-09 16:30:51,869 [1] INFO  LipidCreator.LipidCreator - Using C:\Users\Nils Hoffmann\AppData\Local\Apps\2.0\MPQT09M7.MR0\O893NBD3.RW2\skyl..tion_e4141a2a22107248_0015.0001_b2be94ac8cfe2cb4\Tools\LipidCreator as base directory for relative resource lookup. Resolved executing assembly location: C:\Users\Nils Hoffmann\AppData\Local\Apps\2.0\MPQT09M7.MR0\O893NBD3.RW2\skyl..tion_e4141a2a22107248_0015.0001_b2be94ac8cfe2cb4\Tools\LipidCreator\LipidCreator.exe
2021-06-09 16:30:51,870 [4] INFO  LipidCreator.LipidCreator - Opening connection to Skyline through pipe f909f6a6-06db-4e86-a1ea-2f81d9529f3c
2021-06-09 16:30:51,878 [4] INFO  LipidCreator.LipidCreator - Connected to Skyline through pipe f909f6a6-06db-4e86-a1ea-2f81d9529f3c
2021-06-09 16:31:05,296 [1] ERROR LipidCreator.LipidCreator - An error occured, data could not be sent to Skyline, please check if your Skyline parameters allow precursor masses up to 1464.8057Da.
System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.IO.IOException: Data columns not found in first line.
   bei System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   bei System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   --- Ende der internen Ausnahmestapel�berwachung ---
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei SkylineTool.RemoteService.ProcessClientThread(Object streamArg) in C:\proj\skyline_21_1_x64\pwiz_tools\Skyline\SkylineTool\RemoteService.cs:Zeile 95.
   --- Ende der internen Ausnahmestapel�berwachung ---
   bei SkylineTool.RemoteClient.RemoteCallName(String methodName, Object[] arguments)
   bei LipidCreator.LipidCreator.sendToSkyline(DataTable dt, String blibName, String blibFile)
2021-06-09 16:31:18,122 [1] INFO  LipidCreator.CreatorGUI - Closing LipidCreator!
2021-06-09 16:31:18,123 [1] INFO  LipidCreator.LipidCreator - Disposing SkylineToolClient!
```

**Comment by chemice** [comment] 2021-06-10 07:43
This is a bit annoying. Two new versions of product are not compatible… Can we figure out what Skyline has changed?

From: Nils Hoffmann ***@***.***>
Sent: den 9 juni 2021 16:39
To: lifs-tools/lipidcreator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lifs-tools/lipidcreator] Send to Skyline throws exception on Skyline 21.1 (#15)


Skyline 21.1 with LipidCreator 1.2.0.772 throws the following exception when I try to send a transition list to Skyline.

2021-06-09 16:30:51,855 [1] INFO  LipidCreator.LipidCreator - LipidCreator is connected to Skyline file: ''



2021-06-09 16:30:51,869 [1] INFO  LipidCreator.LipidCreator - Running LipidCreator version 1.2.0.772 in skyline tool mode on Win32NT



2021-06-09 16:30:51,869 [1] INFO  LipidCreator.LipidCreator - Using C:\Users\Nils Hoffmann\AppData\Local\Apps\2.0\MPQT09M7.MR0\O893NBD3.RW2\skyl..tion_e4141a2a22107248_0015.0001_b2be94ac8cfe2cb4\Tools\LipidCreator as base directory for relative resource lookup. Resolved executing assembly location: C:\Users\Nils Hoffmann\AppData\Local\Apps\2.0\MPQT09M7.MR0\O893NBD3.RW2\skyl..tion_e4141a2a22107248_0015.0001_b2be94ac8cfe2cb4\Tools\LipidCreator\LipidCreator.exe



2021-06-09 16:30:51,870 [4] INFO  LipidCreator.LipidCreator - Opening connection to Skyline through pipe f909f6a6-06db-4e86-a1ea-2f81d9529f3c



2021-06-09 16:30:51,878 [4] INFO  LipidCreator.LipidCreator - Connected to Skyline through pipe f909f6a6-06db-4e86-a1ea-2f81d9529f3c



2021-06-09 16:31:05,296 [1] ERROR LipidCreator.LipidCreator - An error occured, data could not be sent to Skyline, please check if your Skyline parameters allow precursor masses up to 1464.8057Da.



System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.IO.IOException: Data columns not found in first line.



   bei System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)



   bei System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)



   --- Ende der internen Ausnahmestapel�berwachung ---



   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)



   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)



   bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)



   bei SkylineTool.RemoteService.ProcessClientThread(Object streamArg) in C:\proj\skyline_21_1_x64\pwiz_tools\Skyline\SkylineTool\RemoteService.cs:Zeile 95.



   --- Ende der internen Ausnahmestapel�berwachung ---



   bei SkylineTool.RemoteClient.RemoteCallName(String methodName, Object[] arguments)



   bei LipidCreator.LipidCreator.sendToSkyline(DataTable dt, String blibName, String blibFile)



2021-06-09 16:31:18,122 [1] INFO  LipidCreator.CreatorGUI - Closing LipidCreator!



2021-06-09 16:31:18,123 [1] INFO  LipidCreator.LipidCreator - Disposing SkylineToolClient!

**Comment by wlstutts** [comment] 2021-06-24 19:09
Hi, I am having the same issue. Has there been any progress with resolving this issue?

**Comment by nilshoffmann** [comment] 2021-06-25 06:39
The relevant code on our side starts here:
https://github.com/lifs-tools/lipidcreator/blob/master/LipidCreator/LipidCreator.cs#L1600

**Comment by nilshoffmann** [comment] 2021-06-25 09:42
The following commit may have changed the behaviour of the Small Molecule transition list handling:

https://github.com/ProteoWizard/pwiz/commit/c909413d7a03a495d02b2dc0fc316fc7480b668d#diff-c4b9161e0835e4c011c0b7cd1d946d474c0d83a3d842bb40aeea2b224d900415

If I export the transitions to csv and then import them via the Skyline import transitions dialog, everything works as expected.
This is the list of the column headers we write out: https://github.com/lifs-tools/lipidcreator/blob/master/LipidCreator/LipidCreator.cs#L203

@bspratt 
@brendanx67
Maybe you have an idea what could be causing this?

**Comment by nilshoffmann** [comment] 2021-06-25 09:55
The following is an example transition list that is successfully transferred via the SkylineToolClient#InsertSmallMoleculeTransitionList method on Skyline < 21.1

[example-transitionlist-string.txt](https://github.com/lifs-tools/lipidcreator/files/6715338/example-transitionlist-string.txt)

**Comment by bspratt** [comment] 2021-06-25 16:18
Hi Nils,

Thanks for the example file. I can reproduce the error and I'll get this
resolved ASAP.

Brian

**Comment by bspratt** [comment] 2021-06-25 17:32
The problem is indeed with Skyline, there was a change to the CSV handling code that got confused by the quotes around the decimal values. Those shouldn't matter, and certainly didn't before, so we'll get that cleaned up in the next Skyline-Daily and the next patch release for the official Skyline release version.

**Comment by nilshoffmann** [comment] 2021-06-25 18:32
Thanks for the update, Brian! 
I will keep this issue open until we have this resolved.
Please ping me if you have a build ready for testing from our side.

**Comment by bspratt** [comment] 2021-06-25 22:34
Have a look at this unofficial build:
https://teamcity.labkey.org/repository/download/bt209/1457407:id/SkylineTester.zip

**Comment by nilshoffmann** [comment] 2021-06-26 10:40
> Have a look at this unofficial build: https://teamcity.labkey.org/repository/download/bt209/1457407:id/SkylineTester.zip

This looks good! Sending of the transitions now works again. Thanks a lot!
However, I noticed that we also can not send a spectral library anymore (since at least 20.2, tested with Skyline 20.2 and the build linked to by Brian above). Interestingly, if I import the attached blib file in Skyline as a new library, it shows up right and there seem to be no errors.

I have attached the LipidCreator log for the relevant part and the blib file (fingerprint library, all m/zs with 100 as intensity) as well as the slc file created by Skyline, too.
[LipidCreator-SpecLib-Issue.zip](https://github.com/lifs-tools/lipidcreator/files/6719933/LipidCreator-SpecLib-Issue.zip)

The exception I get in the log seems to be a non-serializable error (line 800). So I guess something is happening or throwing an exception on Skyline's side, but I can not see the stack trace of it:

```
2021-06-26 11:56:23,294 [1] ERROR LipidCreator.LipidCreator - An error occured, data could not be sent to Skyline, please check if your Skyline parameters allow precursor masses up to 941.4199Da.
System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.Exception: System.Runtime.Serialization.SerializationException: Der Typ "pwiz.Skyline.Model.LineColNumberedIoException" in Assembly "Skyline-daily, Version=21.1.1.176, Culture=neutral, PublicKeyToken=null" ist nicht als serialisierbar gekennzeichnet.
   bei System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   bei System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   bei System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   bei System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   bei SkylineTool.RemoteBase.SerializeObject(Object o) in Z:\pwiz\pwiz_tools\Skyline\SkylineTool\RemoteBase.cs:Zeile 60.
   bei SkylineTool.RemoteService.ProcessClientThread(Object streamArg) in Z:\pwiz\pwiz_tools\Skyline\SkylineTool\RemoteService.cs:Zeile 104.
   --- Ende der internen Ausnahmestapel\FCberwachung ---
   bei SkylineTool.RemoteClient.RemoteCallName(String methodName, Object[] arguments)
   bei LipidCreator.LipidCreator.sendToSkyline(DataTable dt, String blibName, String blibFile)
```
This here: `Der Typ "pwiz.Skyline.Model.LineColNumberedIoException" in Assembly "Skyline-daily, Version=21.1.1.176, Culture=neutral, PublicKeyToken=null" ist nicht als serialisierbar gekennzeichnet.` means that LineColNumberedIoException is marked as non-serializable. So I guess that is why we do not receive it on our side of the client connection.

We are calling this method:
https://github.com/ProteoWizard/pwiz/blob/0fdbda9236fd25181464c305549cf75a0ec4fd03/pwiz_tools/Skyline/SkylineTool/SkylineToolClient.cs#L195

Does Skyline capture exception logs somewhere? Maybe that would help me determine what the reason for this exception might be?

**Comment by bspratt** [comment] 2021-06-28 16:13
We can probably sort this out quickly if you can provide a precise
description of the steps needed to produce the error in LipidCreator, and
the necessary files.

Thanks

Brian

**Comment by brendanx67** [comment] 2021-06-28 16:27
I am willing to release a Skyline-daily soon and include these fixes in the
first Skyline 21.1 patch, which may also be relatively soon. So, as long as
this second issue can be sorted out quickly, you should be in good shape.

**Comment by nilshoffmann** [comment] 2021-06-28 17:27
Hi Brian, hi Brendan! 
Thanks a lot for helping with this. 
I recorded what I did to help you reproduce the issue.
If it should turn out to be something that we need to fix on our side in the end, I will be happy to publish an patched LipidCreator version quickly.
The following GIF shows the behavior. 

1. I installed LipidCreator in Skyline Daily from the Tool Store
2. I activated the output to immediate window to capture the logs
3. Then, I started LipidCreator and activated the Collision Energy Optimization
4. I then add some mediators (for which we have CE models) to my lipid list
5. I continue until the Lipid Transitions Review
6. I tick "Send spectral library to Skyline"
7. I click on "Send to Skyline"
8. I enter a name "testlib" for the spectral library
9. The transitions and the spectral library are successfully transferred to Skyline.
10. I return to the main LipidCreator view and delete the previous lipid list
11. I create a second list of transitions for some Glycerolipids (for which we do not have CE models, so the library entries for each fragment will have a value of 100, e.g. we are generating binary fingerprint spectra)
12. I continue until the Lipid Transitions Review
13. I tick "Send spectral library to Skyline"
14. I click on "Send to Skyline"
15. I enter a name "testlib2" for the spectral library
16. The exception from above is thrown and is output in the immediate window

The spectral library transfer worked before, but maybe we are sending some values in a now wrong format?

![LipidCreator-1 2 0-772-on-SkylineDaily](https://user-images.githubusercontent.com/3309580/123677355-4bbdb900-d845-11eb-821a-c29927ca58d0.gif)

**Comment by bspratt** [comment] 2021-06-29 19:09
Obviously Skyline needs to do a proper job of reporting this, but the
problem is that in
"MoleculeGroup,PrecursorName,PrecursorFormula,PrecursorAdduct,PrecursorMz,PrecursorCharge,ProductName,ProductFormula,ProductAdduct,ProductMz,ProductCharge,Note,PrecursorCE
"TAG","TAG
12:0-12:0-12:0","C39H74O6","[M+NH4]1+","656.5824","+1","precursor","C39H74O6","[M+NH4]1+","656.5824","+1","","-1"
(etc)
Skyline is objecting to the idea of a negative collision energy. That check
demanding CE > 0 was added in August 2020, so it's relatively recent. And,
it seems, inappropriate.

**Comment by nilshoffmann** [comment] 2021-07-02 07:08
So, should we keep using the negative collision energy or should we mutually define a value for "not defined"?

**Comment by bspratt** [comment] 2021-07-02 16:53
I think it depends on whether or not that's a meaningful value for Skyline
to pass along to the mass spec. That is, are we wrong in insisting on a
non-negative value? I could be persuaded that we are, because that check
was only recently added.

On the other hand, if it is important to communicate "No Value", then I'd
think the thing to do is just omit the column altogether.

**Comment by nilshoffmann** [comment] 2021-07-02 17:39
Sorry, I got mislead by the spectral library. So the issue is still in the transmission of the transition lists containing CE values that are negative. 
I would argue that negative values are, to my knowledge, not meaningful, unless collision energy values would also carry some sort of charge. We may however have mixed cases, where some transitions would have proper CE values, while some may not have them. How would Skyline handle such a case, when both proper CEs and "unknown" CEs are sent to the mass spec, i.e. if I had a number of transitions with CEs and a number of transitions without CEs in my working list? Or do all of them have to be defined explicitly?

**Comment by brendanx67** [comment] 2021-07-02 17:53
It would fall back to the CE predictor, which might be "None" and then it
would fail. If the document has a CE predictor (CE = b1 * precursor m/z +
b0 ; by charge state) then not supplying an explicit CE is fine.

**Comment by bspratt** [comment] 2021-07-02 18:14
From what I have seen, most mass specs expect a column to be fully
populated, or not present. It seems like this has been working well enough
until now, I should just remove that check and allow negative values as we
did in the past. With mass specs "Energy" often seems to be a synonym for
voltage", and negative values are certainly legitimate there.

**Comment by brendanx67** [comment] 2021-07-02 18:22
We have been asked in the past by instrument vendors not to allow negative
CE values because their systems don’t allow them. We exclude them from the
ranges generated during CE optimization.

**Comment by nilshoffmann** [comment] 2021-07-02 18:29
Thanks for clarifying this. I think we need to somehow fix that behavior on our side. Not sure that mixed transition list will be 100% avoidable, though if people create multiple transition lists, with and without proper CEs, using LipidCreator and send them to the same document. Tracking this as #16

**Comment by bspratt** [comment] 2021-07-02 19:02
Then I'd say exclude that column altogether when you have no useful values,
and when you have a mix just leave those unknowns as blank cells, or
possibly "N/A" (though I think that would require a change in Skyline to
accommodate).

**Comment by dominik-kopczynski** [comment] 2021-08-30 12:25
The bug is now fixed, the import works works pretty fine now for both the transition list as well as the spectral library. Bug #16 is now also fixed. Thanks everyone for your support :-)

**Closed by dominik-kopczynski** 2021-08-30 12:25 UTC
Labels: bug, 1.2.0, Skyline 21.1
